In [1]:
import torch
print(torch.__version__)

2.8.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Gpu is not available. Using CPU")
    

Gpu is not available. Using CPU


#Creating Tensor

In [8]:
#Using empty
a =torch.empty(2 ,3)
print (a, a.dtype, a.shape)

tensor([[1.2599e-01, 1.7152e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]]) torch.float32 torch.Size([2, 3])


In [9]:
#Using Zeros
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
#Using Ones
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
#Using rand ->random
torch.rand(2,2)

tensor([[0.4067, 0.3650],
        [0.8498, 0.4354]])

In [13]:
#Use of seed
torch.manual_seed(50)
torch.rand(2,2)


tensor([[0.6180, 0.0687],
        [0.3893, 0.0404]])

In [14]:
# Using tensor - custom tensor
torch.tensor([[1,2,3,5],[4,5,6,0]])

tensor([[1, 2, 3, 5],
        [4, 5, 6, 0]])

In [21]:
#Other ways to create tensor

#arange
print("Using arrange ->", torch.arange(0,10,2))

#Using linspace 
print("Using linspace ->", torch.linspace(0,15,3))

#Using eye
print("Using eye ->", torch.eye(5)) #create square matrix

#Using full
print("Using full ->", torch.full((2,3),5)) # all values are 5 in tensor of size 2X3

Using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  7.5000, 15.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])
