# NN module

In [4]:
#Create model
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()

        self.linear = nn.Linear(num_features,1)
        #(input features number , output features number)
        self.sigmoid = nn.Sigmoid()
    
    #Forward pass
    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [5]:
#Create dataset
features = torch.rand(10,5) #10 samples, 5 features

#Create Model

model = Model(features.shape[1])

#Call forward pass
#model.forward(features)
#easy way to call forward pass
model(features)
  

tensor([[0.3980],
        [0.4861],
        [0.3725],
        [0.3817],
        [0.5366],
        [0.4399],
        [0.4409],
        [0.4260],
        [0.4624],
        [0.4759]], grad_fn=<SigmoidBackward0>)

In [8]:
# Show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1910, -0.3124,  0.1084, -0.2408,  0.3688]], requires_grad=True)

In [9]:
#Show bias
model.linear.bias

Parameter containing:
tensor([-0.3825], requires_grad=True)

In [10]:
!pip install torchinfo


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
from torchinfo import summary

summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# With hidden layer 

In [14]:
#Create model with hidden layer 5 ->3 ->1
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()

        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    #Forward pass
    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [17]:
#Create dataset
features1 = torch.rand(20,5) #20 samples, 5 features

#Create Model

model1 = Model(features1.shape[1])

#Call forward pass
#model.forward(features)
#easy way to call
model1(features1)

tensor([[0.6247],
        [0.6270],
        [0.6263],
        [0.6599],
        [0.6476],
        [0.6124],
        [0.6324],
        [0.6527],
        [0.6572],
        [0.6284],
        [0.6537],
        [0.6506],
        [0.6169],
        [0.6602],
        [0.6219],
        [0.6277],
        [0.6081],
        [0.6432],
        [0.6326],
        [0.6440]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Show model  final weights
model1.linear2.weight

Parameter containing:
tensor([[ 0.4804, -0.4779, -0.1804]], requires_grad=True)

In [20]:
model1.linear2.bias

Parameter containing:
tensor([0.5289], requires_grad=True)

In [21]:
from torchinfo import summary

summary(model1 , input_size = (20 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential

In [22]:
#Create model with sequential
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()

        self.network = nn.Sequential(nn.Linear
            (num_features,3),
             nn.ReLU(),
             nn.Linear(3,2),
             nn.ReLU(),
             nn.Linear(2,1),
             nn.Sigmoid()
        )
    
    #Forward pass
    def forward(self, features):

        out = self.network(features)
      

        return out

In [23]:
#Create dataset
features2 = torch.rand(30,5) #20 samples, 5 features

#Create Model

model2 = Model(features2.shape[1])

#Call forward pass
#model.forward(features)
#easy way to call
model2(features2)

tensor([[0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5406],
        [0.5400],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5436],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410],
        [0.5410]], grad_fn=<SigmoidBackward0>)

In [25]:
from torchinfo import summary

summary(model2 , input_size = (30 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [30, 1]                   --
├─Sequential: 1-1                        [30, 1]                   --
│    └─Linear: 2-1                       [30, 3]                   18
│    └─ReLU: 2-2                         [30, 3]                   --
│    └─Linear: 2-3                       [30, 2]                   8
│    └─ReLU: 2-4                         [30, 2]                   --
│    └─Linear: 2-5                       [30, 1]                   3
│    └─Sigmoid: 2-6                      [30, 1]                   --
Total params: 29
Trainable params: 29
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00